spring:
  datasource:
    url: jdbc:postgresql://dpg-cvit4hggjchc73c001hg-a.virginia-postgres.render.com/financemanager_7sc9
    username: uta
    password: nQcEGw5iYlIa82ijyUaLh2U8dCiZAtvA
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db.changelog.xml
    default-schema: public
