spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/FinanceManager
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db.changelog.xml
    default-schema: public

server:
  error:
    include-message: always